### ISSUE TITLE
CF Single tenant version - JWT payload does not include a 'zid' property

### ISSUE THREAD

**Issue by elimase101** [SAP-samples/btp-cap-genai-rag#10]
CF Single tenant version, when pushing sample mails I get the following from the ai-srv-main logs
```
2024-01-02T10:44:54.158+0000 [APP/PROC/WEB/0] STDOUT [odata] - POST /odata/v4/mail-insights/addMails
2024-01-02T10:44:54.164+0000 [APP/PROC/WEB/0] STDOUT GENERATING INSIGHTS...
2024-01-02T10:44:54.823+0000 [APP/PROC/WEB/0] STDOUT {"custom_fields":{"messageContext":"jwt","package":"connectivity"},"level":"warn","logger":"sap-cloud-sdk-logger","message":"Warning JWT: The provided JWT payload does not include a 'zid' property.","msg":"Warning JWT: The provided JWT payload does not include a 'zid' property.","timestamp":"2024-01-02T10:44:54.822Z","written_at":"2024-01-02T10:44:54.822Z","written_ts":1704192294822}
2024-01-02T10:44:56.831+0000 [APP/PROC/WEB/0] STDERR Error: Request failed with status code 403
2024-01-02T10:44:56.831+0000 [APP/PROC/WEB/0] STDERR Error: Cannot read properties of undefined (reading 'text')
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR [cds] - Error: Error: Cannot read properties of undefined (reading 'text')
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR at CommonMailInsights.onAddMails (/home/vcap/app/srv/mail-insights-service.js:193:28)
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR at async next (/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR at async CommonMailInsights.handle (/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR at async /home/vcap/deps/0/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/action.js:53:16 {
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR numericSeverity: 4,
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR id: '1333616',
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR level: 'ERROR',
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR timestamp: 1704192296831
2024-01-02T10:44:56.832+0000 [APP/PROC/WEB/0] STDERR }
```
Any ideas on how to deal with this?
Thank you

**Comment by kay-schmitteckert** [comment]
Hi @elimase101, thanks for reaching out. Looking at the logs and noticing ```status code 403``` during insights generation in the "addMails" endpoint, it seems that your connection to generative AI hub is not established correctly. 

Could you share your destination details (either from the cockpit or during debugging `srv/utils/ai-core.ts`?
If you check your deployments on SAP AI Core, is the respective deployment running?

Best
Kay
